### ISSUE TITLE
Background image suggestions

### ISSUE THREAD

**Issue by marshmallow-teni** [MathiasGruber/TheNinjaRPG#107]
I created a few variations for the background that I think will work better and transition nicer with the layout. 
![TNR BG2](https://github.com/user-attachments/assets/5d921614-e66c-4f48-b38c-7c525f199214)
![TNR BG7](https://github.com/user-attachments/assets/a421233f-9cc1-4d69-baaf-d17dd0f404f3)
![TNR BG9](https://github.com/user-attachments/assets/637a1fe7-6fff-4c1d-8d25-a5b2738c91c7)

**Comment by MathiasGruber** [comment]
Can you save it as png so as to preserve transparency? If I insert as not it'll go like this: 
![image](https://github.com/user-attachments/assets/3ebd5623-1d84-4caa-ad4d-b49115992b76)

**Comment by marshmallow-teni** [comment]
Sure! I'll do it when I get home tonight.
Is there one you like more than the others? or should I just upload all 3?

**Comment by marshmallow-teni** [comment]
![TNRbg](https://github.com/user-attachments/assets/aae4f4f5-8aab-4c06-9eac-cfa9ffbb7560)
![TNRbg2](https://github.com/user-attachments/assets/6c1f95ed-cf26-4378-8eff-d73dc6972cad)
Ok, .pngs that I think should work a bit better? 
There's slight differences between the intensity if the gradient between the two, wasn't sure which would work better

**Comment by marshmallow-teni** [comment]
![TNR BG3](https://github.com/user-attachments/assets/ee263f26-059a-40f9-ba15-e0fdb1834dce)
one more with no gradient at the top

**Comment by MathiasGruber** [comment]
Should be implemented, thank you! :)
