### ISSUE TITLE
Navbar fix

### ISSUE THREAD

**Issue by marshmallow-teni** [MathiasGruber/TheNinjaRPG#108]
I realized the navbar wasn't symmetrical so I made an edit. I changed the shape a little in one, the other i kept the same shape.
![banner](https://github.com/user-attachments/assets/bab0299f-b48e-4881-9724-11d70ccabba2)
![banner2](https://github.com/user-attachments/assets/f2a08033-f4bb-428f-bd5e-41be5f80dd58)

**Comment by marshmallow-teni** [comment]
![navbar-wood](https://github.com/user-attachments/assets/0af79350-b0f8-4c38-9ddb-f963af6638ab)

I also thought texture may look good? However don't know if it would be too busy. Just another thought.

**Comment by MathiasGruber** [comment]
UPloaded, thank you! :)
