### ISSUE TITLE
UX improvements - Part 1

### ISSUE THREAD

**Issue by ReiChan5446** [MathiasGruber/TheNinjaRPG#110]
- Home Page:

- [x] Add login button next to Register
![home page](https://github.com/user-attachments/assets/d84c8e08-5970-4737-8cfd-32b4038b005f)

- [x] Mission Hall: 
-- Move missions completed to the user profile
-- Move daily completed to a more visible location and bigger text.
-- Edit the text for the number of missions available, for clarity.
![mission hall](https://github.com/user-attachments/assets/0af774e2-4ee8-4ace-82ad-f21034ce04a6)

- [x]  Replace the filter button for tabs: Online, Strongest, Leaderboard (PVP streak) and Staff.
![Users](https://github.com/user-attachments/assets/42d2682d-e5ed-4d99-b5bc-cad26b558fdc)

- [x]  Add filter per village and stat classification. 
![infor bloodlines](https://github.com/user-attachments/assets/0d4f719c-c464-45c0-9eeb-8fbd1561e7c7)

- [x]  Prefilter jutsu by stat classification using tabs (5): Taijutsu, Ninjutsu, Genjutsu, Bukijutsu and Highest. 
![info jutsu](https://github.com/user-attachments/assets/89713680-7bf5-40ef-8d63-31150c1032ed)

- [x]  Replace the drop-down for tabs: Global Tavern / Local Tavern (**for regular users only**, keep the drop-down as it is for Staff members)
![GLOBAL_LOCAL TAVERN](https://github.com/user-attachments/assets/5117fa9c-3620-44b4-99d4-ba5d5d07c782)

- [x] Jutsu Management:
-- Prefilter jutsu by stat classification. 
-- Visually display the jutsu element.
![My jutsu](https://github.com/user-attachments/assets/7593e218-136d-47c9-8110-d78d1d915f4b)

Soon, part 2.

**Comment by MathiasGruber** [comment]
All done :)
