### ISSUE TITLE
Prioritized List of Critical Issues during week 32

### ISSUE THREAD

**Issue by d3t0ur** [MathiasGruber/TheNinjaRPG#111]
- [x] Prevent Jutsus above Level 20 refunding gold past level 20.

- [x] - Reflect and Absorb tag should no longer use gens & stats for decrease.

- [x] - Quest/Event Objectives should have a Description & Success Description Text Field; Preferably a pop out box or a collapsible menu

- [x] Some users report still having Fed benefits months after they've cancelled Fed Support

- [x] Lower mission cap to 40. Increase exp ratio to level up. 

- [x] When training jutsus and they level up by combat, the training does not level up the jutsu. eg. If I start training my jutsu from level 9 to 10, and it levels up to 10 through combat, when the training is done, the jutsu will stay level 10. 

- [x] Server reset keeps happening 15 mins earlier each day.  https://discord.com/channels/1080832341234159667/1270588782587936840

- [x] Toggle for completing objectives in sequence (One after the other is complete)
- [x] Reflect and Absorb Tag do not work in AI Battles
- [x] Village tag for bloodlines revert to none after we save

- [x] Max Level for Quests/Events

- [x] - Heal tag activates on every instance of damage. 

- [x] Outlaws cannot do crimes

- [x] Village field on Objectives so we can track objectives by village

- [x] Lower PvP exp gain to on average 50

- [x] Increase Round Timer to 25 seconds

- [x] Reduce Jutsu exp gained in Combat

- [x] Clan Wars do not start
- [x] Add drop item feature for Event Items. (We don't want them to be sellable, but players need a way to remove them from inventory)

- [x] QoL Combat Update: Offense type in battle log is denoted by color. Blue for Nin, Purple for Gen, Red for Buki, Green for Tai
 
- [x] When Players have a summon equipped, they don't get mission rewards. Summons also cause bugs with the Go Again feature
https://discord.com/channels/1080832341234159667/1125461904547127346/threads/1244906888127058014
 
- [x] DecreaseDamageGiven and Increase StatType Highest is using User's highest offense rather than target's highest offense.

- [x] Spectate doesn't update battle log

- [x] Add specific dialog at the end of combat for draws or double knock out.

- [x] Event Items toggle for being purchasable in Wake Island. 

- [x] Activity Streak Not Tracking:
https://discord.com/channels/1080832341234159667/1125461904547127346/threads/1269672614029426698
 
 - [x] Consumable items toggle so they can be used outside of combat
 
 - [x] Clan leaders being able to kick members from clan battles
- [x] Consumables that restore chakra/stamina/health

- [x] Create a transaction search & sync component

- [x] Outlaws should not be able to sleep in village sector
- [x] Battle Arena doesn't work for outlaws
- [x] Allow Outlaws ONLY to see where the Syndicate City is. Outlaw/Syndicate village should be called City of Mei.

 - [x] clan war battle history logs
 - [x] Menu link to spectate clan battles 
 - [x] more co-leaders for clan. 
 - [x] only clan leader or co-leader can accept the clan war battles. 
 - [x] Clan leader and co-leaders can chose the team members for the clan war battles. 
 - [x] Clear/Cleanse applies on round they're used

- [x] Fix Barrier tag so that barrier doesn't block the user's damage. only the enemy.
- [x]  Stats trained above stat caps should be free to reassign. Propose they go to Mission exp rather than paid 15 rep reassign exp. 
 
- [x] Errands no longer count towards daily cap

**Comment by MathiasGruber** [comment]
All fixed, took a bit more than week 32, but lots of things were also added. Closing now :)
