### ISSUE TITLE
Combat UX  Update/Round Timers

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#118]
The goal is to make the combat page the main focus and provide relevant information while hopefully streaming lining the process.  
Example of the finished product:
![image](https://github.com/user-attachments/assets/df2bf57f-f8c5-468f-b3db-22cfb33615de)

**Left Menu:** 

> The left-hand side will stay the same but there are a few adjustments to be made here,
> 
> On the effects side instead of showing 
> Positive effects just listing to infinite examples:
> bukijustu +
> Bukijutsu+
> Bukijustu+
> 
> It would show:
> bukijutsu + 60%
> The percentage being the amount of that is stacked at the current time. The samething will happen for debuff It would just show the negative value that is in effect 
> 
> Removing the long list of buffs and debuffs and just compiling them into an easy to read interface. 
> Below the menu icons there will be a report feature, this feature will allow players to file an ingame report to notify staff that they are stuck in battle or whatever bug that might prevent them from exiting this screen as we are removing the main menu. 

### Right Menu:

> This will show the player that they are fighting against and their bloodline. 
> Below this information  whenever a use select a jutsu or an item it will bring up the jutsu information 
> It will show:
> 
> 1. Jutsu Name
> 2. Type
> 3. Tags present, for the sake of saving space it will only show the name of that tag as shown in the example and what stat/general it targets. 
> We have included Images in the Offense Graphics on Discord In Visuals that can be used for the specific offense type and we can use abbreviations for the generals: 
> 
> - Int for Intelligence
> - Will for willpower
> - Spd for speed
> - Str for strength

- [x] Remember which AI user last fought

- [x] For the battle log Change Damage text color from default red to reflect the color of the offense . This will allow persons to know what offense was used against while guessing what a player does is a part of combat we feel these changes will make persons think more and plan more while also allowing new users not to be overwhelmed with whats is happening in combat. 

**### Combat Round Rework**

- [x] Instead of each combat round being just a single player's actions. Rounds instead of would contain the actions of all players. Eg. Combat begins and initiative is rolled. Player A wins the initiative and goes first.
Round 1.
Player A takes their turn
Player B takes their turn.
Round ends.
Round 2. 
Player A takes their turn
Player B takes their turn.
Round ends.
And so on.
This would streamline the effects of tags, cooldowns, and ease of understanding combat for new players. A 1 round tag would begin the round after it is used and its effects would only last for that round. A 2 round tag takes place in the following 2 rounds.
(Some tags naturally would have effects that activate on the round they are used, eg. Heal. And that doesn't change.)
Cooldowns would be much easier to track and parse because we wouldn't have to factor in both player's turns into calculating the rounds. We would no longer have to track player round vs enemy rounds for some tag effects because rounds are streamlined into one cohesive thing.
And understanding combat for new players becomes much easier when you know that each round you have your chance to act and so does the opponent.

**### Bugs caused by Combat Changed:**
- [x] Cooldown no End turn and Cooldowns not following Round Timer
- [x] Stuns are lasting longer than intended. A Turn stun turns into a two or 3 turn stun
- [x] Tags are stacking to infinite and not ending when their turn is up. This is happening on all tags. 
- [x] Residual is not being triggered at all 
- [x] Player 2 is not getting their turn round 1. It skips them and goes to round 2 [Turn Skipping](https://pastebin.com/VGbQeiw3)
- [x] Reflect tag not doing proper percentage, it seems to be reducing damage then reflecting. So the original damage is 1k, 40% reflect reduces it to 600 but it reflects 40% of 1000 not 600 
- [x] how easy would it be to make it so that when we hide jutsus and items they’re automatically unequipped from players
- [x] Reflect is also reflecting Residual damage, this shouldn't happen. [Reflect Bug](https://pastebin.com/pxDETBkP)
Reflect lasting more than one turn [Reflect Lasting more than one turn](https://pastebin.com/gRxcFxGs) It also lasts at 1.5 turns instead of the turn specified.
- [x] Absorb Lasting longer than turn specified [Absorb](https://pastebin.com/sNMEwW1v)
- [x] Summons/Clones aren't respecting the current round timer and are causing people to get stuck and they never get their 2nd turn
- [x]  Only one summon of each type on the field
- [x] Armor Tags are not stacking
- [x] Recoil tag not triggering
- [x] Heal Lasting the correct turn 
- [x] When you load into Combat all your defensive stats are shown as negatives
- [x] When attacked automatically redirect to battle

- [x] **Item:** Toggle to allow Certain consumable items to not be used in combat
- [x] Accessory Slot on user profile to equip accessories, maximum of 4 can't equip the same type of accessory. 

**### Designated Jutsu **
- [x] This features allows players to select up to maximum 5 jutsu that does not count towards their equipped slot. 2 For normal users. 3 for gold fed. Two more can be purchased for 50 rep each

**### New Tags/Tag Changes:**
- [x] Stun reduces your AP to a set amount instead of losing a turn. Can convert one of the fields to allow us to enter the AP amount that is reduced as power will be used as a percentage to trigger it. 
- [x] Stun Prevent should be reworked to prevent AP from being taken 
- [x] Prevent Buff-Prevents a player from applying a buff on themself(Increase Stat, Increase Damage Given, Decrease Damage Taken)
- [x] Prevent Debuff- Prevents a player from applying a debuff (Increase Damage Taken, Decrease Damage Given, Decrease Stat)
- [x] Prevent Heal-Stops a player from applying to absorb,life-steal, and heal
- [x] Prevent Clear/Cleanse
- [x] Cleanse/Clear when have multiple rounds attached to it, when it fails it tries again on the next round to trigger. The correct interaction is the tag triggers and it lasts for x amount of rounds if it doesn't trigger it doesn't try again.
- [x] Prevent Tags should not clear buffs that were already applied and should not remove armor effects. 
- [x] Raise Exp per level from 80+ to 950
- [x] Lower BA Cap to 40(Tempoary until BA Rework)
- [x] Remove Exp off village protectors
- [x] Pierce: This is a damaged tag, it uses the damage formula. You can't have Pierce and damage equipped, this tag ignores(Decrease Damage Given, and Decrease Stats it also ignores armor buffs.) It's a pure damage tag that ignores defensive stuff.  Tags that boost Damage or stats do not work with this tag(Increase Damage Taken, Increase Stat, Increase Damage Given) Bloodline boost works on this tag. 
- [x] Stealth-Similar to Basic Heal, this is added in combat 40AP 6 turn cooldown, this makes you untargetable you can't perform any actions except move and heal
- [x] Residual Modfier is no longer affect Pierce(It should it was a good way to scale the damage)
- [x] Only allow two jutsu with Pierce tagged to be equipped
- [x] Increase D Rank Roll chance to 30 and C Ranks to 25 B to 5.
- [x] Rob Tag This tag doesn't rob the user and it should only trigger once per round not multiple times it's percentage-based, the current moment it triggers every action, and on every title this tag should not be allowed to stack. Will need a new field for rob amount just for this tag(percentage as usual)
- [x] Bind-Prevent Players from moving or using any movement tags. 
- [x] Damage Modifier for Pierce Tag, Tag is also not being affected by BL boost when it should
- [x] Med nin exp healing scaling shouldn't affect Jutsus with the heal tag on it, only basic heal. Basic heal can only target ally, not self
- [x] Stun is proving this error message when used [Stun not working](https://gyazo.com/78e02976c5e0d3722f7f335ff8112a67l)
- [x]  Add Minimum Level requirement to Jutsu
- [x] Horzontal Line AOE Tag 3 Hexs
- [x] AI Improvements(The ones you mentioned to reduce cost and make AIs smarter, use jutsu rotation and respect jutsu cooldowns and players are able to set what the AI should do)
- [x] Add the AI Weakness field to AI creation. The Weakness field will have a multiplier of up to 300% and can be affected by stat, element,item, or jutsu. When said option is used it will multiply the damage done to the AI 
- [x] Ability to Edit AI Health, Chakra and Stamina
- [x] AI Ignore stat caps/Ability to give them custom stats
- [x] Ability to edit Rank, Bloodline,Clan,Anbu on AI, just custom fields similar to the custom title don't need the dropdowns.  Its to populate the AI profiles for events
- [x] Ability to add Nindo to AI
- [x] Event AI tag, so we can filter AIs by event/Arena/Summoning
- [x] For content pages(Jutsu,AI,Items,Quest) Remove loading all content simultaneously, and the default Page is the filter. Ability to save filters and remove filter selections without needing to refresh the page. Ability to Filter by hidden things. This should speed up the pages.
- [x] Stealth Bug: When player is stealth previous turn, they need to move the next turn for their jutsu be to able to be used. Players can't heal while stealth.
- [x] Ability to Add Badges to Players account
- [x] Add Clans and Anbu to Freedom State
- [x] Give Basic Heal a 10 round Cooldown, Med nin basic heal scaling should not affect jutsu or items. Only basic heal. 
- [x] Allow Staff to get Jutsu slot without paying

**Comment by MathiasGruber** [comment]
All done, closing
