### ISSUE TITLE
Moderator Improvements

### ISSUE THREAD

**Issue by MathiasGruber** [MathiasGruber/TheNinjaRPG#120]
- [x] IP tracking that can flag users who have more than the 2 permitted accounts or with frequent IP changes, device fingerprinting like browser type, os, mac address, email, etc. 

- [x] Some user IPs do not show up

- [x] Login IP logging

- [x] Last core, we could search up a user and it would tell us any accounts that shared an IP with it, we didn't have to copy the IP then go search for that too, that would be good to have again.

- [x] transaction monitoring with some automated scripting that can track in-game transactions and flag unusual activity, like excessive transfers of ryo between accounts without us having to manually dig through bank logs.

- [x] When you filter the users list to top and click a user then go back, you have to redo the filter to set it to top, and it won't let you just open the players in another tab, which makes it really tedious to hunt through individual accounts.

- [x] Training log timestamps

- [ ] automation that can warn us of accounts that are training too perfectly, like if someone's training exactly every 900.00 seconds for days, they're likely a bot, but without us having to manually hunt for a specific person. It would be ideal if hyper specific things like that though wouldn't be visible to the public and just to staff, probably just mod and admin even. 

- [x] some tools to track the rep black market transactions would be good, but I'm not sure what we could really do with it.

- [ ] Set up automated alerts for staff when suspicious activity is detected, allowing for quick action. Include details like IP addresses, account history, and transaction logs. 

- [x] With changelogs on user profiles it currently looks like this: 
Update: Gengar
Updated: {"bloodlineId":"vv45N2En3p8VrNcU2acd8"}
Changed at: Thu Aug 15 2024 by Gengar
Update: Gengar
Updated: {"bloodlineId":"r3nBY_Th4_ZAIUfhx1jdy"}
Changed at: Tue Aug 13 2024 by Gengar
Update: Gengar
Updated: {"bloodlineId":"IxhIoLEmznqdcnc_6MCN9"}
Changed at: Tue Aug 13 2024 by Gengar
could we change it so that it doesn't just show the bloodlineID, it shows the name of the BL and also that it shows what the previous was, like 
Updated: Bloodline changed from Blue blade eyes to Blood enchanted eyes (for example)

- [x] We could use a way to be able to search bloodline and jutsu statistics for names of players with those bloodlines and jutsus, and ideally be able to see their jutsu levels.

- [x] Currently, when a user is reported, the report system shows them the name of the person who reported them, and that causes drama. Only staff should see who reported it. They also get a message saying that they were reported when they get reported. Since a lot of reports are invalid, can we have a user only be notified of a report when and if we take action on it? If we clear a report, they have no need to know that it existed, they just immediately bring it into the tavern calling out the person who reported them.

- [x] Numerical assignments for all reports (Incident numbers) which can be hyperlinked to reference tickets in other tickets/dupes/etc. 

- [x] being able to see the last 2 or 3 names of a person. If we need to reset a name due to appropriateness we could reset to the last known name. Also makes it easier for people trying to change names to avoid bans.

- [x] Time stamps on reports so we can scroll to see conversations in context.

- [x] i personally wouldn't be comfortable with content admin being able to ban or do Stat resets if they become available. They are not mods and can interfere in investigations by being too hasty.

**Comment by Bugliketheinsect** [comment]
Was told I was good to play. Now am rebanned. Is it intentional, or a bug? User Eko.

**Comment by KyoRuedrig** [comment]
Banned users can change avatars, this is being used to harass players while banned through the avatar system, can this please be adjusted so banned users can not change avatars?

**Comment by KyoRuedrig** [comment]
Also there still seems to be a few users whose IP addresses are not shown in the user system, ie MK3F, and even my account KyoRuedrig.

**Comment by MathiasGruber** [comment]
Completed all these points, except the ones related to automated detection of foul play - that could be week-long endeavour, and so will have to be postponed to release :)
