### ISSUE TITLE
Banned again

### ISSUE THREAD

**Issue by Bugliketheinsect** [MathiasGruber/TheNinjaRPG#121]
Was told by Gengar I was good to play. Been playing. Just got rebanned, but all prior info still says Infraction Cleared. Is it intentional, or a bug? User Eko. Edit* can access some content again. Notification says Banned though.

**Comment by Bugliketheinsect** [comment]
Who's a good boy? WHOS A GOOD BOY? Me!

We should unban me. I'm clearly a goodboy.

**Comment by MathiasGruber** [comment]
This was resolved
