### ISSUE TITLE
Black Market QoL

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#122]
1. One player can only have 3 Maximum Listings
2. Minimum amount of Reps to list is 5
3. Ledger for Admins and Mods to see who purchased what 
4. Player ability to sell Rep Directly to a player they do this by setting up a trade where seller enters rep players name and amount they are charging and then it's sent to the buyer to accept it in the black market
5. Player ability to Delist after 72 hours

**Comment by MathiasGruber** [comment]
Should be implemented now
