### ISSUE TITLE
Conversations updatedAt probably not being updated?

### ISSUE THREAD

**Issue by Northern-Fayt** [MathiasGruber/TheNinjaRPG#124]
Was checking out inbox and I noticed there's a sort on the getUserConversations api call but when a conversation receives a new comment it's not being pushed to the top.

I'm guessing that when a new comment is added to a conversation, updatedAt isn't being updated on the parent table.

Would be nice to see when the comment came in from the inbox screen too. Maybe replace the createDate of the conversation with updatedAt?

Happy to put in a PR to fix this if someone want's to confirm I'm correct about updatedAt not being updated.

**Comment by MathiasGruber** [comment]
I'd absolutely love to get a PR on it :) .. I'm super keen for people to contribute to the project 👍
