### ISSUE TITLE
Increase Damage Given Tag is broken

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#125]
The tags that are specifically on bloodlines go "Increase damage given by target" due to the nature of it, is currently boosting none elemental stuff also. For example, I went Shiroi Youso which should specifically boost only the 5 elements tagged. Yet, I was getting the same results with a none elemental jutsu tagged of the same power. This was brought up by Gengar and we tested it. Lux which is Light element and is boosted by her was doing around the same amount as her Clone Barrage which is none elemental. 

Also this extends to every bloodline in the game. Every A Rank instead of just boosting the elements tagged, it also boosts the none elemental tags.

TLDR: The bloodline tag "increase damage given by target" is boosting none elemental along with the elements attached. 

A possible fix to this I assume would be to make it so those tags ONLY boost what we tag in the element box and include a none element tag so we can specify if a bloodline also boosts none elemental stuff like BEE/BBE/EM.

The 1st screenshot is an elemental jutsu. The 2nd is a none elemental jutsu while I was on SY. The none elemental damage should be much lower.  Closer to my 3rd which was my damage when I switched the tag off the damage increase. This was just to test if the tag is properly working and boosting. And as mentioned above. It seems like it is working, but boosting everything. (edited)
![image](https://github.com/user-attachments/assets/1e637cec-31a2-49cb-96f7-11c2c431fcb9)
![image](https://github.com/user-attachments/assets/a873fb88-5719-44a3-b730-88cc831a9058)
![image](https://github.com/user-attachments/assets/9947fb50-eee6-41ba-ab38-0a6c63eb007b)

The way I think we want it to work more specifically on bloodline tag (The jutsu one seems to be working properly.) is as also mentioned above, to allow us to let the bloodline only give the boost to the elements in the box, and include a none element in there while also removing the automatic damage boost from the tag. This should fix all of the bloodlines in one go if that's even possible.

![image](https://github.com/user-attachments/assets/d239de18-9077-43b8-b9d6-642c8c866db7)

^ Example EM has Water, Fire, Wind, YingYang. Since stats is Highest it should be perfect to boost none elemental

SY however, even though it has 5 elements tagged if the user utilizes as jutsu that is not attached to those elements, they wouldn't get a boost since the Stats Box is empty

![image](https://github.com/user-attachments/assets/39c0ab42-1f17-4f2e-9d7c-6c8655525f2a)

Also Bloodlines can't be unhidden

**Comment by MathiasGruber** [comment]
The tag used on jutsu and bloodlines is the same, and I think it should keep being so, to keep the logic a little streamlined.

I like the idea of adding a "None" element; this would apply to both jutsu & bloodlines. 

Let's just agree on a few scenarios, to make sure we are aligned on the logic:

Effect with Fire+None vs Attack with Fire - **Apply**
Effect with Fire+None vs Attack with Ice - **Ignore**
Effect with Fire+None vs Attack with Ice+None - **Apply** (?)
Effect with nothing specified - Attack with Ice - **Apply**
Effect with nothing specified - Attack with None - **Apply**
Effect with Fire - Attack with None - **Ignore**

Agreed? Did I miss any scenarios?

**Comment by theeneon** [comment]
Correct. So we only apply the effect when they attack with that specific effect.

**Comment by MathiasGruber** [comment]
Should be functioning now?
