### ISSUE TITLE
Wake island event mission hidden coordinations

### ISSUE THREAD

**Issue by Oakward2** [MathiasGruber/TheNinjaRPG#126]
Hi, I started the cat finding mission on the wake Island but after about 3 travels the next one is not showing and the coordinates are 'hidden'. I waited about 4 hrs waiting to see if it was timed but its not and I cannot continue the mission.

**Comment by d3t0ur** [comment]
That is meant to be like that. The location is hidden on purpose. You are to use clues given in the mission to find the hidden location.

Also this is not the place for reporting an issue like this. Our official Discord has a bug report section and a content ticket system that you can use for these issues. The github is for coding related suggestions/fixes/issues only. Apologies for the extremely late response.
