### ISSUE TITLE
QoL Update 2

### ISSUE THREAD

**Issue by d3t0ur** [MathiasGruber/TheNinjaRPG#127]
- [x] Fix Element Icons
- [ ] Update Bloodline page to accurately direct players to Wake Island, not the hospital
- [ ] Increase/Decrease Heal tags should read "themselves or others"
- [ ] Free Stat Respec for Content/Content-Admin
- [ ] Remove All Button for Equipping Jutsu

**Comment by MathiasGruber** [comment]
Thanks, all should be there now :)
