### ISSUE TITLE
my account is bugged 

### ISSUE THREAD

**Issue by erido24** [MathiasGruber/TheNinjaRPG#13]
on my account it is saying that my jutsus are full 5/5 yet I only have 4 equipped since one more of those jutsus were removed in the lastest patch.

**Comment by MathiasGruber** [comment]
This should be fixed in recent commits, please confirm?

**Comment by MathiasGruber** [comment]
Closing due to no response

**Comment by erido24** [comment]
Hello thank you for the email I have checked my account and the sonic slash
ai only justsu is still on my account as a usable Justin and it needs to be
removed please and thank you
