### ISSUE TITLE
backgrounds

### ISSUE THREAD

**Issue by marshmallow-teni** [MathiasGruber/TheNinjaRPG#131]
Here are the seasonal backgrounds in case you wanted to update with the seasons.
I can easily change any issues.

![tnr-fall-background2](https://github.com/user-attachments/assets/7da59bd9-b437-4917-8048-cbc1f41d505c)
![seasons-winter](https://github.com/user-attachments/assets/2a01b638-0a2b-47a7-a887-4da5042f3d2a)
![tnr-seasons-spring](https://github.com/user-attachments/assets/d3500872-397d-4446-ba63-5a0ec482cf86)

**Comment by MathiasGruber** [comment]
These are implemented with following seasonal settings:

![image](https://github.com/user-attachments/assets/bbc70d02-e5b1-4717-8d5c-7b511d6e9afe)
