### ISSUE TITLE
Halloween images

### ISSUE THREAD

**Issue by marshmallow-teni** [MathiasGruber/TheNinjaRPG#143]
I added a halloween twist to two of the elements for the design which could be fun.
![fall banner2](https://github.com/user-attachments/assets/bd4415d0-3942-41e5-8b46-32b2327f9b23)
![jutsuhands](https://github.com/user-attachments/assets/7dafb7a1-f015-40e0-aa13-b2291be1b4bb)

**Comment by marshmallow-teni** [comment]
![Uploading tnrforest.png…]()

**Comment by marshmallow-teni** [comment]
![Uploading tnrforest.png…]()

**Comment by marshmallow-teni** [comment]
![tnrforest](https://github.com/user-attachments/assets/d2eecfa8-a94f-4de7-81dd-e7a059eaf94c)

**Comment by MathiasGruber** [comment]
Merged, thank you! ❤️
