### ISSUE TITLE
Better Prompts

### ISSUE THREAD

**Issue by ReiChan5446** [MathiasGruber/TheNinjaRPG#149]
I edited the prompts we are currently using for the panel for 2 reasons:
1. To ensure consistency.
2. To give proper use of this tool that we are not using otherwise.

In addition I'd like the panel to include a field box where we can set ${prompt}, maybe place it just right under the picture.

New Prompts :

**"quest"**
Epic composition, cinematic ${prompt}, vibrant background,  pixel art evoking the charm of 8-bit/16-bit era games with modern shading techniques, Trending on artstation, 8k, Japanese inspiration, extremely detailed.

**"item"**
Miniature Icon Object for Videogame User Interface, ${prompt}, white background, concept art design, Japanese inspiration, pixel art evoking the charm of 8-bit/16-bit era games with modern shading techniques, MOORPG Items, professional videogame Design, Indi Studio, High Quality, 4k, Photoshop.

**"badge"**
${prompt}badge Japanese inspiration, white background,  pixel art evoking the charm of 8-bit/16-bit era games with modern shading techniques, professional videogame Design, High Quality, 4k, Photoshop.

**"jutsu"**
epic composition, symbolic representing the action: ${prompt},Japanese inspiration, fantasy pixel art evoking the charm of 8-bit/16-bit era games with modern shading techniques, trending on artstation, extremely detailed.

**"Bloodline"**
epic composition, symbolic representing the heritage: ${prompt},Japanese inspiration, fantasy pixel art evoking the charm of 8-bit/16-bit era games with modern shading techniques, trending on artstation, extremely detailed.

**"ai"**
A full-body anime-style pixel art ${prompt} in a 3D-like, standing in a balanced, central position. The ${prompt} is rendered with clean, sharp pixel details and modern shading techniques, evoking the style of retro 8-bit/16-bit games but with a polished, high-quality finish. The background is a simple, solid color highlighting the character, allowing them to stand out clearly. Dynamic pose, extremely detailed.

**Comment by MathiasGruber** [comment]
Thanks, it's been merged! 👍
