### ISSUE TITLE
I'm trying to install it on my vps server via docker but I couldn't do it, is there a chance to install planetscale for free? 

### ISSUE THREAD

**Issue by TrinityGale** [MathiasGruber/TheNinjaRPG#156]
I'm trying to install it on my vps server via docker but I couldn't do it, is there a chance to install planetscale for free?

**Comment by MathiasGruber** [comment]
In the current docker setup we emulate planetscale locally with mysql and a http proxy. What errors do you get?

**Comment by TrinityGale** [comment]
now it says it couldn't find the tnr container, I reinstalled it but is there a video or something I can watch and learn

**Comment by MathiasGruber** [comment]
I've reconfigured how to run the application.. could you let me know if it now works better?
