### ISSUE TITLE
New Bugs 11/1124

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#167]
- [x] Residual are not stacking but overwriting each other
- [x] Adjust Clear/Cleanse to be 60AP
- [x] Allow Moderators, Head Mods,Mod Admin ability to make announcements(notifications)
- [x] API did not reset. Error is in coding.  (30,000 Exp in Compensation for Missions/BA/Training missed)
- [x] Stun should not be cleansable
- [x] Prevent players from being able to tag Movement jutsu  and Summoning Jutsu to their AI profile. Only affect players and not AIs
- [x] When an effect is on the ground the player has to move for the effect to take action. 
- [x] #178
- [x] When using Life Steal or absorb players can over heal to increase their HP :
![image](https://github.com/user-attachments/assets/04cc7c2c-1efd-4477-9f42-57991f8d93b1)

- [x] Heal Reduction still doesn't affect Lifesteal and Absorbs 
- [x] Update User Bandolero activity streak to 92 and give them like 120k exp for not being able to log in for 22 days

- [x] #179
- [x] double clicked the A rank mission and it took 2 missions but I only have 1 active A rank mission.
- [x] Ground Tag: When a Residual is set for ground tag it isn't applying the damage over time. It applies an upfront damage but that's it. What should happen is as long as they are on a tile that is affected by the effect it applies the effect to them, if they move out of it the effect stops. 
- [x] Allow Heal Reduction to work on Life Steal and Absorb, Allow Increase Heal to affect Life steal and Absorb 
- [x] Heal Prevent should block Life steal and Absorb as well as heal
- [x] Only allow 3 Jutsu with residual modifier above 0
- [x] Timer freezing on profile:
![image](https://github.com/user-attachments/assets/505c72b3-56bb-429f-b73d-55baddc85d63)

- [x] AIs does not end turn when they don't have an action todo or can't perform an action they just keep trying todo the something over and over 
- [x] AIs should not try to move on to the same tile/ try to occupy the same space 
- [x] #171
- [x] Clear should affect prevent debuff
- [x] cleanse should affect prevent buff 
- [x] Shows up when a user is dead but they are still active in combat they are unable to DKO with the AI which is what should happen. Player has to end turn and then die.

![image](https://github.com/user-attachments/assets/3811840c-3666-4196-8c7d-9b4a459421bd)

- [x] On the points page remove: PS: Points do carry to final release! 
- [x] Add Clear and Cleanse as basic actions(similar to heal) 10 Round Cooldown  40 AP Cost. 
- [x] Reward Jutsu does not work
- [x] Prevent Debuff must work on Recoil, Heal reduce, Residual damage
- [x] ModifyAI Distance rules: Distance higher than or = /  Distance less than or = 
- [x] Reduce Clan Battles to 3v3
- [x] And one more thing... When we have static assets like barriers and such, the game puts the targeter underneath the asset. Is it possible to layer it so that the target highlighter is always on top of whatever assets we put?
- [x] Another bug we've noticed is that when tags are applied to Ground and Empty_Ground, the effect doesn't stay on the ground for the tag's duration. We would like it so that when we have a jutsu with for example Recoil, and it targets the Ground or Empty_Ground instead of a user, then the effect stays on the ground for the tag's duration and affects users who path over the affected hex.

**Comment by d3t0ur** [comment]
Instead of removing Movement jutsus, the AI move into and overlap with each other. The AIs should be smart enough to not occupy the same hex at the same time.

Additionally, I believe the AIs need an End Turn option after checking if all other options are unavailable to them. That should also alleviate some of the bugs we're seeing with AI

**Comment by d3t0ur** [comment]
Another bug we've noticed is that when tags are applied to Ground and Empty_Ground, the effect doesn't stay on the ground for the tags duration. We would like it so that when we have a jutsu with for example Recoil, and it targets the Ground or Empty_Ground instead of a user, then the effect stays on the ground for the tag's duration and affects users who path over the affected hex.

**Comment by d3t0ur** [comment]
And one more thing... When we have static assets like barriers and such, the game puts the targeter underneath the asset. Is it possible to layer it so that the target highlighter is always on top of whatever assets we put?

**Comment by MathiasGruber** [comment]
Closing this one :)

**Comment by theeneon** [comment]
There's one more bug in coding

________________________________
