### ISSUE TITLE
Village Registration Change 

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#173]
Remove the option of selecting a village at Character creation and after the user has done the initial creating they are taken to a page with a nice background where they have to answer these questions that will choose what Village they are assigned to. 

Questionnaire: Discover Your Village
Question 1: What environment feels most like home to you?

- Sunny deserts and glowing sands. (Shine)
- Mystic forests with ancient trees. (Tsukimori)
- Icy mountains and snowfields. (Glacier)
- Rain-soaked swamps and hidden lagoons. (Shroud)
- Windy valleys and open skies. (Current)

Question 2: Which element do you feel most connected to?

- Fire, for its burning passion. (Shine)
- Earth, for its steady and grounding strength. (Tsukimori)
- Ice, for its sharp and enduring calm. (Glacier)
- Water, for its adaptability and flow. (Shroud)
- Wind, for its freedom and swiftness. (Current)

Question 3: What type of activity do you prefer?

- Harnessing the power of the sun for creation. (Shine)
- Walking peacefully through lush nature. (Tsukimori)
- Conquering harsh challenges with persistence. (Glacier)
- Embracing storms and adapting to change. (Shroud)
- Soaring through the air and embracing speed. (Current)

Question 4: How do you approach a problem?

- Dive in headfirst with fiery determination. (Shine)
- Think it through with patience and wisdom. (Tsukimori)
- Stand firm and outlast it. (Glacier)
- Flow around it, adapting as needed. (Shroud)
- Hit it from an unexpected angle. (Current)

Question 5: What kind of landscape inspires you the most?

- A desert shimmering under a blazing sun. (Shine)
- A tranquil forest alive with spirit energy. (Tsukimori)
- A frozen peak under a starry sky. (Glacier)
- A misty swamp buzzing with hidden life. (Shroud)
- A windswept valley under a vast, open sky. (Current)
- 

Question 6: What motivates you the most?

- The brilliance of success and glory. (Shine)
- Harmony with the world and others. (Tsukimori)
- Overcoming the toughest obstacles. (Glacier)
- Faith and resilience through adversity. (Shroud)
- Freedom and the thrill of the unknown. (Current)

Scoring:
Assign 1 point to the corresponding village for each answer selected.
At the end of the questionnaire, the village with the most points will be the player’s assigned village.
In case of a tie random selection between the ones that got the most votes 

Player gets a free village transfer at Chunin just in case they don't like their village.

**Comment by MathiasGruber** [comment]
👍 .. really like this idea, I've been planning to do a registration overhaul soon, as it seems we are losing players at this stage due to confusion.. will prioritize this soon-ish
