### ISSUE TITLE
Emergency Bugs in Coding

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#180]
- [x] Unlimited Exp Glitch for Combat
- [x] Prevent Buff/Debuff is lasting 2.5 turns instead of the 2 turns.You  have to do a another action for it to  wear off on the  terr that it ends 
- [x] Life steal does not affect absorb 
- [x] Visual Bugs on Ground effects showing up as 1 round instead of the round assigned by the jutsu:
![image](https://github.com/user-attachments/assets/56a3dd4a-ccd9-4023-89bf-f72c55c9eb91)

- [x] Allow Content Admin and Mod Admin to change players Villages(need this for a tournament)

**Comment by MathiasGruber** [comment]
Should all be fixed
