### ISSUE TITLE
Jutsu that are set to enemy, can't be used in Spars as it's considered an ally in the spar so the jutsu won't work

### ISSUE THREAD

**Issue by MathiasGruber** [MathiasGruber/TheNinjaRPG#193]

**Comment by MathiasGruber** [comment]
Need more information here, with specific details on how the jutsu was set up, and potentially a picture of how it's not working; i.e. does it not allow targeting, does it just not apply damage, or what is the specific mode of failure? 

When testing locally it seems to work for me.

**Comment by theeneon** [comment]
This was fixed in your last update.
