### ISSUE TITLE
In MPVP Combat, allies are counted as enemies. Opponent tag does not work in MPVP either due to this.

### ISSUE THREAD

**Issue by MathiasGruber** [MathiasGruber/TheNinjaRPG#194]

**Comment by MathiasGruber** [comment]
This description is somewhat unclear? what is an "opponent" tag? what is the mode of failure? Ideally a copy-paste image of the tag setup, and of the mode of failure.

**Comment by theeneon** [comment]
This happened in Clan Battle. 

Bug 1:
To recreate, go into a clan battle use Staff Test Aoe Damage your allies are counted as enemies so they get hit by your jutsu even with friendly fire set to enemies only: 
![image](https://github.com/user-attachments/assets/a6c81f38-185d-46c7-82f1-affef0abd3b4)

 
The opponent target selector is broken in MPVP, it does not work to recreate go into a clan battle and use Staff Test - Opponent 

Also if your allies is in the target sector you can't use the jutsu when it should just not damage your allies but the action is able to go off. 

The opponent tag works as we tested it in Battle Arena, it works in single player combat. 
We believe this is why we are having issues with spars and friendly fire.
