### ISSUE TITLE
Range indicator starts counting from 0 instead of 1.(You have them set to give +1 range)

### ISSUE THREAD

**Issue by MathiasGruber** [MathiasGruber/TheNinjaRPG#195]
More information needed on this one - when I set the range to 1, it usually is a range of 1 away.

**Comment by theeneon** [comment]
![image](https://github.com/user-attachments/assets/a713ccc3-f74b-452e-ac35-0e14964dd6ce)

I believe it starts on Range 3 to 5 where they all have +1 range on them.

**Comment by MathiasGruber** [comment]
Fixed
