### ISSUE TITLE
Ground Effects are bugged again. 

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#197]
- [ ] After your stun fix, effects that apply to the player as long as they are standing on that hex are no longer working. 
- [x] #199

Would this not be fixed by just creating a tag field so we can decide where the effect is applied to the ground or to the person? 

The issue we are having now is that secondary effects are not applying only damage is so a tag that states apply to other_user or apply to the ground or apply to self.

**Comment by MathiasGruber** [comment]
Should be fixed now
