### ISSUE TITLE
Best way to access back-end logs

### ISSUE THREAD

**Issue by rauf543** [MathiasGruber/TheNinjaRPG#198]
Working on quests right now, and this question might be extremely stupid but it’ll make my life 100x easier.

whats the best way to access console.logs or some sort of logs from the back-end? I run the code as described in the readme and just get a console inside the dev container, I can’t see anything that actually happens inside the system (for e.g through the routers)

i’d like to pepper in a few console logs to understand where my codes breaking.

again probably a stupid question but I thought its better to ask rather than spend 14 hours trying to figure it out. Thanks again!

**Comment by MathiasGruber** [comment]
If you type:

`docker ps`

You'll see what containers are running. You can then get the logs by typing:

`docker logs nextboilerplate-app-1`

If you're in vscode, I usually have the docker-extension installed. Then through the extension, you can click the "View Logs" on the app container.

![image](https://github.com/user-attachments/assets/ac3069bc-9e0f-4963-b780-12e3c5bf65d4)
