### ISSUE TITLE
Priority Bug:Basic Movement doesn't work

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#201]
https://discord.com/channels/1080832341234159667/1312125863851986954

**Comment by d3t0ur** [comment]
I believe I might have found the bug causing this. The basic movement action needs to have rounds of 0 attached to it because of the recent ground and empty ground changes.

**Comment by MathiasGruber** [comment]
Thanks for the hint regarding rounds - wasn't quite the fix for basic movement, which had to be excluded from round logic for whether to pass it to next round, but meant I could fix quickly. Closing this.
