### ISSUE TITLE
SEO Optimized Landing Page

### ISSUE THREAD

**Issue by MathiasGruber** [MathiasGruber/TheNinjaRPG#202]
Right now we show the news on the landing page, which is messing us up, because the content changes constantly, and mis-used html elements may screw with our SEO score. Instead we need a text-based (with images) introduction to the game, which we can SEO optimize.

**Comment by ReiChan5446** [comment]
#### **Welcome to TNR: The Ninja Role-Playing World of Seichi**

Are you ready to forge your own ninja legacy? TNR is a **free, multiplayer online role-playing game** (RPG) where your decisions shape your destiny. Set in the rich world of Seichi, this game offers endless possibilities. Will you rise as a **Kage**, a rogue ninja, or a clan leader? The choice is yours!
![Epic ninja PvP battle in TNR's multiplayer world_](https://github.com/user-attachments/assets/e75ec57e-792d-442c-9ebf-03f391d0a16e)

Alt Text Suggestion: "Epic ninja PvP battle in TNR's multiplayer world."
---

### **Why Play TNR?**

#### **1. Unmatched Roleplay Freedom**
- Align with your village or become a rogue ninja.
- Pursue power, revenge, or loyalty to your people.
- Every decision you make builds your unique story.

#### **2. Thriving Multiplayer World**
- Join other players shaping the evolving ninja world.
- Forge alliances, compete in epic PvP battles, or conquer missions as a team.

#### **3. Master Your Ninja Path**
- Unlock powerful **Bloodlines** and train diverse **Jutsus** to define your combat style.
- Team up with **clans** to share knowledge and dominate the battlefield.

#### **4. Be a Leader**
- Fight your way to the top and claim the title of **Kage**.
- Lead your village to greatness, or carve your own path as a rogue force.
![Players collaborating in clans and villages in TNR RPG_](https://github.com/user-attachments/assets/f3ded97f-72ec-4b7b-a7be-6fb8713217f3)
Alt Text Suggestion: "Players collaborating in clans and villages in TNR RPG."
---

### **Your Ninja Journey Begins Here**

In TNR, you're not just a player—you're part of a community. Whether defending your village or striking from the shadows, you'll leave your mark in this living, breathing world. The only question is: what will your legacy be?
![Start your ninja journey and master jutsus in TNR_](https://github.com/user-attachments/assets/f0d64b24-20f6-4981-a138-703d249205f0)
Alt Text Suggestion: "Start your ninja journey and master jutsus in TNR."
---

**Comment by MathiasGruber** [comment]
Love the images, I will use those as well.. the text will probably dynamically change over time as I get input from the SEO results :)
