### ISSUE TITLE
Mobile Layout Bugs

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#203]
![image](https://github.com/user-attachments/assets/389eac7d-4085-4697-85fb-ddddd6536621)

Player has to scroll up but the page options are still cut off. Might need to move some of the options for mobile 

The cookie bot is also blocking a menu option

**Comment by theeneon** [comment]
![image](https://github.com/user-attachments/assets/74e61c16-8774-4337-aa47-6f0475f87971)
Players are unable to view bottom bar

**Comment by ReiChan5446** [comment]
- [ ] The Alt text for the image prevents you from clicking on the village menu.

![image](https://github.com/user-attachments/assets/c404c882-a6f5-4684-8f72-4e3ec236bc1c)

- [ ] The inbox button could be replaced by "Your Home " page instead, that would be more helpful.

![image](https://github.com/user-attachments/assets/0ec9d255-0617-4371-8e21-daf77532c45c)

- [ ]  You can see the map while asleep, you should not. 

![image](https://github.com/user-attachments/assets/54bb173a-63bb-452f-bc69-fa7b73156bbb)
