### ISSUE TITLE
Item,Village and Jutsu Images not Loading/Layout Images

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#206]
One player reported that they started to load when they turned on a VPN Maybe check uploadthing? 

![image](https://github.com/user-attachments/assets/01904b8e-93c9-4110-b7ff-b6e94eb645ab)

**Comment by MathiasGruber** [comment]
Have not been able to reproduce, is this still happening? Which specific VPN?

**Comment by theeneon** [comment]
Still happening: Mostly on mobile it seems 
![image](https://github.com/user-attachments/assets/d43eb871-5b19-48f5-b79d-5e0cc1cb38f9)


They didn't state which VPN

**Comment by MathiasGruber** [comment]
Is this still happening now?

**Comment by theeneon** [comment]
Safe to close we haven't seen it happen
