### ISSUE TITLE
PRIORITY: Clan Hall Issues

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#210]
I'll have to discard your rules for this one. We're hosting a 3V3 tournament and the clan hall keeps bugging out people getting crashes etc and being stuck after fights. Can you grant me the ability to delete clans which refreshes everyone's state so we don't have them getting stuck Thats the error that pops up. 

Basically what's happening is that their clan hall isn't registering that the fights are over and other clan isn't there 

![image](https://github.com/user-attachments/assets/302f9bec-2cc6-45d6-8502-e1fb0dae0ed9)

Also allow me to remove players out of clans 

If possible it would be good to wipe every clan's state as players are out of clans, the clans are deleted and they can't join a new battle

**Comment by MathiasGruber** [comment]
Should be fixed now?
