### ISSUE TITLE
Review: clone tag

### ISSUE THREAD

**Issue by MathiasGruber** [MathiasGruber/TheNinjaRPG#24]
This tag summons a clone of the user to fight alongside them in combat.
A percentage of user stats they will be like AI’s but will drain the users Chakra for a certain amount.
and will only last for a certain amount of rounds

**Comment by theeneon** [comment]
For the creation of summons, we need the ability to add the jutsu and health the summon would use and the percentage of the user stats that is copied over to the summon along with how long the summon will last.

**Comment by theeneon** [comment]
For the clone tag specifically, we need the turn limit of how long the clone will last, and what the clone will use in battle along with the percentage of stats that are taken over and the health of the clone to allow to balance the tag.

**Comment by MathiasGruber** [comment]
Clone tag reports: https://discord.com/channels/1080832341234159667/1164109598739922955
