### ISSUE TITLE
New System: Missions, Errands, Crimes

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#38]
**### Missions and Errands**

All Missions, Errands, and Crimes can be created and edited from the content panel and all completed missions will be tracked from the player's log book(coming soon) to grant them achievements for completing x amount of missions. 

Missions and Errands are the main way for the users to earn Ryo, they are divided into the following ranks based on difficulty:
- S Ranks
- A Ranks 
- B Ranks
- C Ranks
- D Ranks 

Each mission rank will be tied to an in-game rank, for example:

- Jonin has access to S ranks and below
- Chuunin has Access to B Ranks and below
- Genin has access to C Ranks and below 
- Students do not do missions but will be able to do errands

Missions are intended to be the main way of earning Ryo but as a substitute the gains from Errands will be lower than that from Missions, to compensate however,

Outlaws are not able to do Errands

They're three types of Errands:

- Garbage Collection: Players are asked to pick up garbage around their village which will grant them Ryo
- 
- Baby Sitting: This is a time-based errand that will last for an hour which players
- 
- Delivery: This errand will ask the player to leave their village and travel to a random coordinate within the same sector where they have to collect an item and bring it back. 

Rewards for each errand are collected from the errand menu. 

(Numbers to be decided later on gain of ryo/stat)

### Type Of Missions/Crimes Available:
Missions can be divided into two main categories PVE and PVP-related. 

PVE missions will take place on the map at different sectors and coordinates where the player has to travel the world to get that mission accomplished. Missions can have multiple stages for example:

Part 1 You go to X location and collect something
Part 2 You must now escort it to a different location while fending off attacks by random AIs on the map. This is the PVE component and its aim is to bring life to the huge globe that we have. 
Part 3 You return to your home village to accept your reward. 

The main types of PVE Missions/Crimes are:

- Fetch Missions/Crimes: Go to this location on the map, collect the item, and bring it back. 
- Assassination Missions/Crimes: Go to a single or multiple locations and defeat a single or group of opponents,
- Intelligence Missions/Crimes: Infiltrate a location on the map and gather documents
- Escort/Bodyguard Missions/Crimes: travel to a location where you will be attacked at random by AIs until you reach the destination. 
- Gather Resources for your village 
- Capture Missions/Crimes: The player must infiltrate a location and capture a target 

Another aspect of Missions/Crimes is PVP, where players can enter a Mission Lobby where one player will be assigned a task/duty and another player will be asked to deal with it. 

Types of PVP Missions:

- Racking up a certain amount of kills against a certain Village/Another player is tasked with stopping them from doing this
- Infiltration: Depending on the user's generals there will be a percentage chance of them being able to gain information about a village infrastructure, or sabotage said infrastructure to weaken it or steal a village jutsu scroll to learn village secrets. 
- Espionage: Steal information from other users
- Assassinate/Guard User x must protect an NPC to x coordinate while another user has been tasked with the assassination of such NPC and the bodyguard 

For coordinates, the game can generate the coordinates of the objectives so that it takes them to where new each time.

**Comment by MathiasGruber** [comment]
This is more or less implemented, so closing this for now :)
