### ISSUE TITLE
Rank System

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#39]
List of Ranks and level Requirements to take the promotion exam 

-  Academy Student Level 1
- Genin Level 10
- Chuunin/Lower Outlaw Level 20
- Jonin/Higher Outlaw Level 40
- Special Titles that can be gained through the “Prestige System” 
- Elite Jonin/ Warlord
- Sannin (should probably make this Sage as, San, which means three unless we make this a three-person capped title) I thought of that but it's easier recognizable this way for persons who watch the show  

Ranks in Core 4 will function more as a cosmetic achievement than a restriction-based system, some things will be restricted but by and large a Rank will serve as an accomplishment rather than something you train and aim for. 

### Academy Student:
This is one of two introductory ranks in the game where we will be teaching persons how to play the game there are things that are restricted but granted Ideally it should take 4-8 hours for a player to hit level 10, we propose a 1k per level system at Academy student 

### Rank Benefits and Restrictions:

- Can’t Leave Village
- Can’t be attacked or engage in PVP outside of Sparring 
- Can only train  D Rank Jutsu
- Can only Purchase D Rank Items

### Promotion Exam

 Requirements:
Must be Level 10
Must have 100 AI Battles Completed 
Must have three Jutsu's trained

Promotion Exam, with flavor text and images:

“You step into the room with your Sensei sitting at a table, you are asked to perform the three basic jutsu that all students must know”
A dialog box should come up asking for the user to select the 3 basic jutsu i.e. Clone, Transformation, and Replacement Jutsu. 
After successfully performing the 3 they are granted Genin. 

###  Genin
The second introductory rank would have the same leveling system as before with 1k exp needed to rank up for each level. 

### Rank Benefits and Restrictions:

- B Rank Missions and Above are blocked 
- Can’t Learn any jutsu above C Rank 
- Can Purchase Items up to B Rank
- Can do D and C Rank Missions
- Is able to leave the village
- Able to participate in PVP(Genin vs Genin only)
- Can Roll for their Nature Element
- Unable to level pass level 20

**Promotion Exam:**

- Needs to complete 30 D Rank Missions
- Needs to complete 30 C Rank Missions
- 50 PVP Fights fought
- 250 Arena Battles Completed
- 10 Jutsu Trained
- Level 20

### Chuunin Exams:

The promotion exam is a three-part quest that mirrors the show:

Part 1:

Written Exam, this exam will be a trivia on TNR things they can find in-game and general game knowledge, to pass The player must get 80% and above 

Part 2:
The user must find two scrolls that will be scattered on the map, Once this part of the exam is active, the players will have to go to a sector and fight two AIs to collect each scroll. Once the scrolls are picked up they can then return to the village and complete the final part of the exam.

Part 3:

This is a PVE part where the player will be asked to fight against 3 different AI’s in back-to-back battles.  The AIs will be of level 21 and 22 strength respectively. Once all 3 are defeated the player will be promoted to Chuunin where they will be able to level up further. 

### Chuunin:
At this rank, we assume the players have fully understood the game and no longer need handholding as such there are not many things that are locked off at this level. 

- Rank Benefits and Restrictions:
- Can Train Jutsu up to A Rank
- Can Roll for second Element
- Can do Missions up to A Rank
- Can Participate in Tournaments
- Can do PVP
- Can participate in PVE Raids and events
- Able to Join all Occupations
- Can create Clans/Factions
- Can become clan elder
- Can Leave Village to become Outlaw(At this time they gain the rank Lower Outlaw)
- Unable to become Village Elder
- Can Purchase Items up to S Rank
- Can learn Village jutsu 
- Can train to level 100 
- (there might be more but we’ll add as needed)
- 

There are no Jonin exams as it’s a strict promotion

- Rank up Requriements: 
- Level 40
- 200 B Rank Missions/Crimes Done
- 150 A Rank Missions/Crimes completed
- Two Jutsu at Level 100
- 100 PVP battles won
- 500 Battle Arena Done

**Jonin:**
The final rank of the game, Jonin canon was really just a title given out to the elites as such it serves the same purpose in the game, Though there are a few things that only Jonins get access to:

- Can become Kage
- Can become Village Elder
- Can become Sensei 
- Can train S Rank jutsu
- Can do S Rank Missions/Crimes
- 

At this level, we expect that these players are the best in the game but to add an additional layer to it this is called the “Prestige System”

### Prestige System:

This is a work in progress but what it does is that it unlocks an additional title for players to strive for, the first in this title system is Elite Jonin this isn’t a rank but a title to showcase someone who has accomplished things in the game and dedicated time to his village.

**Comment by MathiasGruber** [comment]
Closing this thread now, as we've implemented restrictions for all the ranks in terms of the systems that are currently there. Will use this issue for reference when new systems are create, such as clans etc.
