### ISSUE TITLE
Typescript conversion of SpriteMixer.js, TrackBallControls.js and OrbitControls.js - $10 reward

### ISSUE THREAD

**Issue by MathiasGruber** [MathiasGruber/TheNinjaRPG#4]
My OCD is not dealing well with these adapted javascript snippets taking from `three.js` documentation are not typed. Reward sent view paypal for anyone willing to update these.

**Comment by GhostDogo** [comment]
No idea what I'm doing just yet, but wanna jump in feet first when I get home. If anyone else with experience jumps in too, I'd love to learn from ya.

**Comment by MathiasGruber** [comment]
Yep, exactly, those files are copy-pasted (with only minor changes) from the `https://github.com/mrdoob/three.js/` github - however, they are all in javascript. If they could all be converted to `.ts` and comply fully with our typescript & linting rules, that'd be awesome :)
