### ISSUE TITLE
Log Book

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#56]
### What is the Log Book:

The Log Book serves as a diary of the player's progress throughout the game, it will cover tutorials, missions, events, and achievements, a place for persons to view badges, and collect awards. The log book will also be where persons go to take the rank-up exam. 

The logbook will be located on the player profile page, there will be a visitor-facing logbook that shows the player's badges and their nindo when you bring up a player's profile.  

Objectives: These are a list of things the user must complete each objective will have 3 tiers with increasing difficulty, some objectives will act as a tutorial for players while others will be achievements that can be claimed. Each tier will give a reward and at the end of completing all 3 tiers, the user gets the final reward. 

### Some of the objectives may be:

- Daily Task(PVP kills, Missions completed, time spent training, PVE done)
- Missions Completed separated by Rank
- Kills
- Stats Trained(Milestone achievements i.e reach 10k trained ninjutsu etc)
- Time spent in one village(After each milestone an award is given this ties into the prestige ranks and titles that will be available to persons) 
- Anbu Kills 
- Tournaments won
- Village Funds Earned
- Jutsu’s Mastered
- Students Trained

More objectives to be added later on 

Achievements: After completing objectives are doing noticeable things(Becoming a Kage, anbu, clan leader etc) These are claimed here and the respective badges are displayed on the user profile for all to see. Also for completing objectives users can get ryo, rep jutsu, bloodline, and items. 

 Quest: The Logbook is where players will go to accept event quests during event times. There will be a tracker to explain what the current details are and a timer to state how long the quest will be active. 

 Missions: Players can see the current 
a mission they are on and the progress towards completing it as some missions will have multiple parts. 

 Rank up: The Log Book is where persons will go to take their Rank Up Exams. Depending on the rank, they must fulfill the criteria and then pass the exams. 

The system is still in its infancy and over time will look to expand on it.

**Comment by MathiasGruber** [comment]
Implemented in #63
