### ISSUE TITLE
My Account Bugged

### ISSUE THREAD

**Issue by KagaUchi** [MathiasGruber/TheNinjaRPG#7]
Hey Terr, for some odd reason when I enter comeback I cannot Flee use Jutsu or Move and sometimes it doesn't show my HP depletion... and it seems that the only way to exit battle is if im killed or my foe flees. please look into this cause im the only one having this issue. 

KagamiUchiha

**Comment by MathiasGruber** [comment]
Are you till experiencing this?

**Comment by MathiasGruber** [comment]
Closing due to no response
