### ISSUE TITLE
Moving bug

### ISSUE THREAD

**Issue by Kmgaoy** [MathiasGruber/TheNinjaRPG#70]
The travel function has a bug 
![Screenshot_2024-02-09-13-12-45-42_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MathiasGruber/TheNinjaRPG/assets/159535705/d5ab2199-bfb1-48a3-adba-7d4c299565fb)
![Screenshot_2024-02-09-13-02-38-73_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MathiasGruber/TheNinjaRPG/assets/159535705/e14d8d50-ff99-4659-a2c8-f9b4e379d1b2)

**Comment by MathiasGruber** [comment]
Seems like it's been fixed
