### ISSUE TITLE
Has a pvp daily even though I'm genin

### ISSUE THREAD

**Issue by Yojidormakun** [MathiasGruber/TheNinjaRPG#76]
I go by Dormammu on the game, and apparently for my daily I got pvp kills even though I'm a genin and then I was put into a pvp that said I was sparring, I was killed by a chuunin called Friigod, maybe I am missing something somewhere, if so disregard but for now I am unsure on what is happening.

**Comment by MathiasGruber** [comment]
This should have been fixed by content team
