### ISSUE TITLE
getting attacked 

### ISSUE THREAD

**Issue by XSeoulXReaperX** [MathiasGruber/TheNinjaRPG#77]
Good Afternoon,

the game is great so far and im glad that its back. one thing i see that could be an issue for the future is letting ranks chunnin and up attack genins. i get that war is a feature of the game but as a genin you stand absolutely no chance when fighting someone in a different rank than you are.

**Comment by MathiasGruber** [comment]
This is being looked into before release, thanks for the feedback :)
