### ISSUE TITLE
Occupations(Anbu, Med-Nin, Sensei)

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#80]
Their will be 3 main occupations in the game, Anbu, Medical Ninja and Sensei.

> **### Anbu:**
> To gain access to Anbu you must be Chuunin, and have the required village prestige. Anbu squads are created by the Kage or Chief of Anbu. A Village can have a maximum of 10 Anbu squads, each containing 20 persons. Each squad will have a name, a leader and a co leader. 
> 
> When players enter the Anbu hall, they will have a general Anbu Orders(Kage and Cheif are the only ones that can post these orders)  and each squad will have their personalize orders that he leader and co leader of the Anbu Squad can edit. 
> 
> Anbu Squads will be tracked by their kills and village funds and tokens gained. 
> 
> Anbu members receive an increase in tokens and village funds they also receive a 5% discount on ninja tools and hospital fees. 
> Only Anbu members, Kage, Village Elders can view the Anbu Hall and it’s orders 

> ### **Medical Ninja:**
> Med nin can be accessed at Genin, their 3 levels to it. Medical Ninjas will be able to heal persons who are in the hospital to full health and will be able to heal persons inside of combat. 
> 
> The amount a medical ninja can heal is dependent on their level and it will cost Chakra to do so. 
> Using basic heal, they will be to perform healing.  The chakra cost will scale with the amount of HP that is needed. 
> 
> 
> The healing will work as follow: 50 Chakra to heal 100 HP This would make it that it would take 2500 chakra to heal a fully capped user at 5000 HP. However the more experience the healer is their will be a percentage reduction. 
> 
> - Novice: No reduction. 
> - Apprentice: 10 reduction
> - Master 25 Reduction 
> 
> The experience requirement are as followed: 
> To reach Apprentice you need 5000 Exp
> To reach master you need 10000 Exp
> 
> For every time they heal someone they gain 10% of the total heal amount as exp. 
> The medical ninja will go to the hospital to heal someone, they will see a list of persons who are in the hospital the option to heal will be present, when they select it they can choose to heal 25,50,75 and 100% of the targets current health. 
> 
> To add more agency to the medical ninjas, hospital prices will go up and scale with HP at higher rate, when you pay to leave the hospital you will be fully healed . This is similar to core 2 to give the Medical Ninjas people to actually heal. 
> 
> Medical ninjas healing is also available in combat where they can heal their allies. The Strength of basic heal will be tied to their medical ninja level. 
> Novice: Heal 5% of missing health
> Apprentice: Heal 10% of missing health
> Master: Heal 15%  of missing health

> ### **Sensei:**
> To become a Sensei, you need to be Jonin, a Sensei can only have three students at any given time and they must be Genin. 
> 
> The training times are reduced for Genins when learning Jutsu by 5% when they have a teacher.  For every completed mission their Students take the Sensei will receive 1000 Ryo. 
> Students will show up on the Sensei's profile and vice versa

**Comment by MathiasGruber** [comment]
All done, closing issue :)
