### ISSUE TITLE
Quality of Life Updates version 2 

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#85]
> The ability to apply multiple filters to search for Jutsu, example:
> Rank, Stat, Element, Effect, power
> This will allow for better searching and finding what area is lacking. 
> -Able to view your learned jutsu while sleeping
> -pvp streak fixed when fighting ai
>-Sell the Item at a 50%  loss 
>-Ability to level up Jutsu by using it 1000 xp per level 30 xp gain every time it's used. 
>-Convert Chakra and Stamina to static instead of percentage 
>-Pop up for Missions similar to the Level-up screen instead of the small notification at the bottom of the screen. 
>-Ability to change the name of the person who's making news and notifications for events and stuff 

-War kills displayed on public profile. (War participation, IE Kills, buildings taken over etc)
![image](https://github.com/MathiasGruber/TheNinjaRPG/assets/7893509/60a413bd-3488-43ca-b861-68875c54cc20)

NEW TAGS/Re-WORK OF TAGS
> - Stun Prevents needs to be a percentage chance instead of static
> - Clear: Percentage chance to Remove all positive effects of the user(so increase damage dealt, decrease damage taken etc, everything that is green for the user when they apply it) Right now this tag also clears bloodline effects which shouldn't happen. 
> - Cleanse Percentage chance to Remove all negative effects applied to the user 
> - Item tag called Quest that automatically deletes from user inventory when the mission it’s tied to is completed
>- Increase/Decrease Armor no longer works 
>- Absorb Tag Change it so that Absorb does not reduce the amount of damage taken while healing. How the tag works now if someone does 500 damage it will reduce the damage and then convert that damage to hp/cp/sp. What should happen is that the full 500 damage is dealt and they absorb a percentage of whatever that is. 
>-Recoil: User takes a percentage of damage dealt to themselves.( While HP cost is nice it doesn't accomplish what we need sometimes
>-Increase/ Decrease Heal no longer works. Should also be a percentage as well
>-Life Steal: Heal for a percentage amount of damage dealt
>- Reflect tag only works when the values are very high

**Comment by MathiasGruber** [comment]
Closing this. War kills point moved to war issue and user jail feature created for user ban restrictions.
