### ISSUE TITLE
Jail(Banning Players) 

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#88]
Jail is where Players will be sent when they are banned by a Moderator. 

When player log in they will receive a notification(similar to the level-up screen) That they are banned with the reason for being banned and time left on their ban. 

Players can be jailed for life(permanently banned Admins Only privilege.) or for hours based on the rules and guidelines. 

While in Jail players are not able to access

1. Tavern
2. Inbox
3. Village Hall
4. They are unable to access Home to sleep
5. Unable to leave the village
6. Unable to access any village-related buildings outside of the training ground
7. Unable to Access Battle Arena or Spar
8. Only 8 hour training option is available 
9. Unable to Purchase Rep

**Comment by MathiasGruber** [comment]
All implemented, closing issue
