### ISSUE TITLE
Black Market/Federal Support

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#89]
> **Bloodline Shop**
> 
> Divided into two, the ability to buy bloodlines outright and the ability to select a random bloodline. 
> 
> **Random Shop:**
> 
> - Chakra Laced Quartz  Give Random D Rank BL 70 Rep
> - Ruby Star Ring Give Random C Rank BL 80 Rep
> - Sapphire Wave Pendant Give Random B Rank BL 90 Rep 
> - Sulfur Wing Wing Give Random A Rank BL 100 Reps 
> 
> Specific Shop This allows persons to buy the Bloodline that they want outright without the random roll:
> 
> - A Ranks Cost: 200 Rep
> - B Ranks Cost:  190 Rep
> - C Rank Cost: 180 Rep
> - D Rank Cost 170 Rep
> 
> Stone of Heraldry: 10 Rep to remove BL 
> 
> Slithering Tentacle: Ability to keep re-rolling for an S Rank. This is S Rank or nothing. Using the same chances as their first roll. Cost 60 Rep per roll. 
> 

> **Ryo for Rep Shop**
> 
> This is a Player-to-player exchange where they can exchange Rep for Ryo.
> 
> The player can list the rep that they have bought in exchange for Ryo. 
> 
>  Once they list it, it’s taken from their account and it can’t be delisted until after 7 days. 
> The format would look like this:
> 
> Name of player Rep Ryo Purchase 
> 
> 
> After 30  days all listings are removed.  

**Stats/Jutsu Load Outs**

> - Exchange Stats: 10 Rep
>- +1 Inventory Slot  10 Rep
>- Elemental Affinity Re-Roll(If Bloodline gives an element they can't re-roll that element) 15 Rep

- Jutsu Load Out Page  40 Rep

> **Purchase Federal Support**
> - Blue Fed: 15 Rep
> - Silver Fed: 35 Rep
> - Gold Fed: 50 Rep

**Misc Stuff**
- Avatar borders - for federal supporters 35 Rep(Coming soon) 
- Highlight badges, can select a badge to make it bigger on their profile 2 Rep

>- Custom Title( Will appear in brackets beside your name on your profile and in the tavern)  5 Rep
> - Name Change: 5 Rep

**Federal Support Overhaul** 

> Blue Fed: 
> 
> - Blue username
> - +2 Inventory Space
> - Custom Avatar 512KB
> - One Extra Jutsu Slot 

**Silver Fed:**

> - Silver Username
> - +5 Inventory Space
> - Custom Avatar 1MB
> - Two Extra Jutsu Slots
>- 5% Bank Interest

- Two Jutsu Loadouts

**Gold Fed:**

> - Gold Username
> - +10 Inventory Space
> - Custom avatar 2MB
> - Three Extra Jutsu Slots
>- 8% Bank Interest

- 3 jutsu Loadouts 

Features to Discuss/Implement

Ability to Reskin structures in villages to show different backgrounds/icons

**Comment by MathiasGruber** [comment]
All features implemented except reskinning, which will be future release
