### ISSUE TITLE
Beta Prep QoL List

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#94]
# Fixed
- Staff Ability to Jump to village taverns without leaving their village 
- Hidden BLs must not show up to be rollable 
- GPS Pin for the highlighted sector  when searching for  sector 
- Lower Battle Immunity to 1 minute
- Increase Prestige Cost for Kage to 1000, prestige is taken every time they challenge. After a challenge, the Kage can’t be challenged again by that user for the next 3 days. 
- Change Village Coordinates:
    Glacier: 203
    Silence 293
    Shroud 254
    Current 271
    Konoki 305
    Shine 83
- sectors that need recolor: 272  green
- Basic attack power level to 15
- Remove Village Swap for everyone except staff
- Leave Village Button to become an outlaw 
- Rejoin Village Button when inside a village sector but all training and regen is cut in half for 5 days
- Remove BL swap for everyone except Content team
- Confirmation Pop up when Buying fed with Rep 
- Double the amount of gains from PVP 
- Lower Jutsu hard cap to 25
- The battle wait timer is reduced to 10 seconds, Round timer is increased to 20 seconds
- Allow Content to add Ryo cost for Jutsu
- Show amount of users online with a number not minutes active
- The percentage doesn’t work on Home Regen
- Student Level cap 10
- Genin Level Cap 20 (20k stat cap implemented here)
- Jonin Level Cap 100
- Jutsu that can’t be trained must not be able to be used in battle
- Mods ability to Check activity Logs(See if players are botting, what actions were done on the account). We will not store all that data, can now see number of too fast infractions on public profile.
- Anbu receives tokens for every PVP kill not just War PVP
- Scouting Button For raiding a village with the level, rank, and attack buttons. When they click attack it will take them to the person if they are not on the same coordinates as them 
- Mods ability to remove nindo and titles in case they violate rules 
- Confirmation button for everything that spends rep
- Away to check Player reports on profile
- Away to check purchase history(admins only)
- IP Check(For players who are trying to ban evade/have multiple alts)
- an extra classification for BLs calledd H Rank
- Green Border Around Allys Red for Enemes Blue for Neutral
- Ability to Ban player from Taverns not just game
- Add AI Weakness to certain jutsu/items
- Ability to force a name change
- Ability for Content Admins to Gift players BLs, Items, Jutsu
- Ability for Content Admins to Gift players BLs, Items, Jutsu
- Mission/Event AI Category on Creating AI
- When AI/Summonings have multiple jutsu attached it only uses one and ignores the cooldowns
- Order Bans, warnings, and reports by most recent and active(Makes it easier to look up bans and reports)
- A way to issue an official warning that will leave an infraction on player's account that can be checked 
- Events do not show up coordinates only information that is placed in the description box 
- Content Admin ability to increase all gains by 2,4,8X for some time
- Chakra/Stamina cost decrease per level
- Regen is changed to per minute instead of second

# Right before release
- Banned users stay ban after reset

**Comment by MathiasGruber** [comment]
We should refund fed payments as reps for beta/release. If not possible, some other way reward people for having supported through fed.
